### ISSUE TITLE
Compatibilité laptop

### ISSUE THREAD

**Issue by dzogrim** [Chelsea486MHz/RockyLinux-ANSSI-BP-028#2]
Bonjour,

Super projet. Merci !
Est-ce qu'il est compatible d'emblée avec du hardware en changeant par exemple le disque `vda` pour `sda` (ou peut-être sur un `nvme0n1` 🤷🏻‍♂️ sur quelque système) via `TARGET_BLOCK_DEVICE` ?
Pour une utilisation hors VM… ou bien n'est-ce pas suffisant pour démarrer et installer ce _build_ via `UNetbootin` ou `dd`, voire `Etcher` (et même `Raspberry Pi Imager` 💯 ) ?

Merci 

Séb

**Comment by dzogrim** [comment]
N. B. J'avoue avoir essayé sans succès… 
Je me cogne des erreurs bloquantes au démarrage de type
```
Started cancel waiting for multipath siblings of nvme0n1 
```
ou encore 
```
trying to find a root image on the device /dev/sda1 
```

**Comment by Chelsea486MHz** [comment]
Le système est bien compatible avec des machines bare-metal.

Je ne distribue pas de telle image car de mon expérience professionnelle les industriels préfèrent durcir une VM redéployable qu'un système bare-metal sur lequel la virtualisation sera complexe.

Pour ce qui est de cette erreur:

`trying to find a root image on the device /dev/sda1`

Je vais avoir besoin de plus d'informations: quelles sont les modifications apportées, quel est le protocole d'installation, et quelle est la machine cible ?

**Comment by dzogrim** [comment]
Bonjour,
Merci beaucoup pour cette réponse.
Je comprends, et c'est top pour de la VM ! Bravo 🥇 

Je n'ai changé que le "**TARGET_BLOCK_DEVICE**" (a priori c'est `nvme0n1` sur ce laptop) et ajouté un paquet et un user dans _kickstart_, autant dire quasi aucune modification (sauf après quand j'ai remplacé le _quiet_ en _debug_).

J'imagine que ça pourrait être un problème de driver ou quelque chose dans le genre / voire firmware… et là je suis sur un _HP EliteBook 830 G10_ (sans secure boot) via une "bête" clé USB (flashée avec tout ce qui était possible de tester à ce jour comme indiqué plus haut) — testé aussi avec un SSD…

![IMG_0476](https://github.com/Chelsea486MHz/RockyLinux-ANSSI-BP-028/assets/4758578/d873599b-0c04-4a78-ae9e-035da6fcda59)

Ce qui me perturbe un peu et m'inquiète pour le matos, c'est que le procédé fonctionne pourtant avec l'[ISO officielle Rocky Linux DVD 9.3](https://download.rockylinux.org/pub/rocky/9/isos/x86_64/Rocky-9.3-x86_64-dvd.iso)… 🥺 malgré tout. Alors que la machine coute 1.4 k€ 😅

**Comment by Chelsea486MHz** [comment]
L'installation est démarrée avec les paramètres noyau suivants:

`initrd=initrd.img inst.stage2=hd:LABEL=%NEW_ISO_LABEL% quiet inst.ks=cdrom:/%PATH_KICKSTART_MAIN%`

La machine s'attend à lire le kickstart depuis un CD-ROM, pas une clé USB. Il est donc nécessaire de modifier le kickstart selon le guide officiel de Red Hat pour des installations par clé USB.

Accessoirement, si je puis me permettre, c'est une très mauvaise idée d'installer ce système sur une machine utilisateur et encore plus sur une machine portable. Sur un serveur, c'est très bien car il est possible d'automatiser dans une CI la création de chaque image pour chaque machine et de les configurer pour netboot ces dernières (permettant ainsi une résilience aux attaques avec reconstruction de la machine à chaque boot). Cette approche permet l'inclusion dans chaque image des secrets, clés cryptographiques, et configurations réseau uniques à chaque machine.

Si vous arrivez tout de même à installer ce système sur votre machine, vous serez ensuite confronté à plusieurs problèmes comme par exemple l'impossibilité de la mettre à jour sans recompiler le noyau avec tout vos modules.

Je vous recommande d'installer une distribution appropriée pour votre machine portable. Si la sécurité ou l'intimité de l'information est importante à vos yeux, des alternatives comme Tails ou Qubes sont préférables.

**Comment by deajan** [comment]
> Bonjour,
> 
> Super projet. Merci ! Est-ce qu'il est compatible d'emblée avec du hardware en changeant par exemple le disque `vda` pour `sda` (ou peut-être sur un `nvme0n1` 🤷🏻‍♂️ sur quelque système) via `TARGET_BLOCK_DEVICE` ?

De mon côté, je détecte le premier disque (vda/sda/hda) via un script dans kickstart, permettant de généraliser le kickstart a pas mal de machines. Mais effectivement, je devrais ajouter le support nvme, cd https://github.com/netinvent/rhel9_scripts
Preneur de potentiels tests ;)
